library(shiny)
library(formatters)
library(gt)
library(tidyverse)
library(rlistings)
install.packages("shinythemes")
library(shinythemes)
install.packages(c("htmlwidgets", "jsonlite", "crosstalk", "htmltools"))
install.packages("DT")
library(DT)